- name: Push to Other Master
  copy:
    src: "join/{{ inventory_hostname }}/tmp/"
    dest: /tmp/
  with_items: "{{ groups.master }}"

- name: Set Variable
  shell: cat /tmp/join_control_plane
  register: join

- name: JOIN
  shell: "{{ join.stdout }}"      

