apiVersion: v1
kind: ConfigMap
metadata:
  name: sematec-website
  namespace: my-ns
  labels:
    app.kubernetes.io/name: sematec-website
    app.kubernetes.io/env: development
data:
  API_URL: https://api.sematec.ir
  APP_URL: http://app.sematec.ir
  DB_HOST: db_host1.sematec.local
  DB_USER: DB_USER
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sematec-website
  namespace: my-ns
  labels:
    app.kubernetes.io/name: sematec-website
    app.kubernetes.io/env: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: sematec-website
      app.kubernetes.io/env: development
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sematec-website
        app.kubernetes.io/env: development
    spec:
      containers:
        - name: nginx
          image: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
          envFrom:
            - configMapRef:
                name: sematec-website
          env:
            - name: BANK_URL
              value: https://bmi.iran.gov.ir
            - name: SMS_URL
              value: http://sms.bmi.iran.gov.ir
          volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
