- name: Push to Other Worker
  copy:
    src: join/k8s-m1/tmp/
    dest: /tmp/

- name: check JOIN Worker
  stat:
    path: /etc/kubernetes/pki
  register: __pki

- block:
  
  - name: Set Variable
    shell: cat /tmp/join_worker
    register: join
  
  - name: JOIN
    shell: "{{ join.stdout }}"

  when: not __pki.stat.exists

- name: Pause for 5 minutes to build app cache
  ansible.builtin.pause:
    minutes: 2
