- name: Set timezone
  timezone:
    name: Etc/UTC

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}" 

- name: Add hostname to hosts (Line-1)
  lineinfile:
    path: "{{ hosts_path }}"
    regexp: '^127\.0\.1\.1'
    line: '127.0.1.1 {{ hostvars[item].ansible_host }}'
    owner: root
    group: root
    mode: 0644
  when: hostvars[item].ansible_host is defined  
  with_items: "{{ groups.haproxy }}"

- name: Add hostname to hosts (Line-2)
  lineinfile:
    path: "{{ hosts_path }}"
    regexp: '^127\.0\.0\.1'
    line: '127.0.0.1 {{ hostvars[item].ansible_host }}'
    owner: root
    group: root
    mode: 0644
  when: hostvars[item].ansible_host is defined  
  with_items: "{{ groups.haproxy }}"

- name: Add hostname
  lineinfile:
    path: "{{ hosts_path }}"
    line: "{{ hostvars[item].ansible_host }} {{item}}"
    state: present
  when: hostvars[item].ansible_host is defined  
  with_items: "{{ groups.all }}"

- name: Unlink resolv_conf
  file:
    path: "{{ resolve }}"
    state: absent

- name: Create resolv_conf
  file:
    path: "{{ resolve }}"
    state: touch

- name: Set DNS
  template:
    src: resolv.conf.j2
    dest: "{{ resolve }}"

- name: Install HAProxy Packages
  apt:
    pkg:
      - keepalived
      - haproxy
      - psmisc
    state: present
    update_cache: true

- name: Load_Balancer_Config
  include_tasks:
    file: Load_Balancer.yml

- name: KeepAlived_Config
  include_tasks:
    file: keepalived_config.yml
