hosts_path: "/etc/hosts"
resolve: "/etc/resolv.conf"
fstab: "/etc/fstab"
docker: "/etc/apt/sources.list.d/docker.list"
containerd: "/etc/containerd/config.toml"
sysctl: "/etc/sysctl.conf"
kubernetes_minor_version: "1.30"


# DNS Config (SHEKAN)

shekan_dns:
  #- 194.104.158.78
  #- 172.29.2.100
  - 85.15.1.15  
  - 185.206.92.250
  #- 10.202.10.202
